package api_v1

// generated by lightweight-swagger-codegen@eaglesakura

import (
	"encoding/json"
	"github.com/eaglesakura/swagger-go-core"
	"net/http"
)

// 環境変数を示すオブジェクト
type EnvironmentValue struct {

	// 環境変数名
	Name *string `json:"name"`

	// 環境変数値
	Value *string `json:"value"`
}

// encode to json
func (it EnvironmentValue) String() string {
	buf, _ := json.Marshal(it)
	return string(buf)
}

type EnvironmentValueArray []EnvironmentValue

func (it *EnvironmentValue) Valid(factory swagger.ValidatorFactory) bool {
	if !factory.NewValidator(it.Name, it.Name == nil).
		Required(true).
		Valid(factory) {
		return false
	}
	if !factory.NewValidator(it.Value, it.Value == nil).
		Required(true).
		Valid(factory) {
		return false
	}

	return true
}

func (it *EnvironmentValue) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (arr *EnvironmentValueArray) Valid(factory swagger.ValidatorFactory) bool {
	for _, it := range *arr {
		if !factory.NewValidator(it.Name, it.Name == nil).
			Required(true).
			Valid(factory) {
			return false
		}
		if !factory.NewValidator(it.Value, it.Value == nil).
			Required(true).
			Valid(factory) {
			return false
		}
	}
	return true
}

func (it *EnvironmentValueArray) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
