package api_v1

// generated by lightweight-swagger-codegen@eaglesakura

type MachineState string
type MachineStateArray []MachineState

const MachineState_Running MachineState = MachineState("Running")
const MachineState_Shutdown MachineState = MachineState("Shutdown")
const MachineState_None MachineState = MachineState("None")

func (it MachineState) Ptr() *MachineState {
	return &it
}
func (it MachineState) StringPtr() *string {
	temp := string(it)
	return &temp
}
func (it *MachineState) Value() MachineState {
	return *it
}

func (it *MachineState) StringValue() string {
	return string(*it)
}
func (it MachineStateArray) Ptr() *MachineStateArray {
	return &it
}

// Exist Patterns
var MachineStatePattern []string = []string{

	"Running",
	"Shutdown",
	"None",
}

func (it *MachineState) Valid(pattern []string) bool {
	if it == nil {
		return false
	}
	value := string(*it)
	for _, v := range pattern {
		if v == value {
			return true
		}
	}
	return false
}
